version: '3.8'

services:
  redis:
    image: "redis:latest"
    container_name: "my-redis-container"
    ports:
      - "6379:6379"
    networks:
      - course-enrolment-network

  mongodb:
    image: "mongo:latest"
    container_name: "my-mongo-container"
    volumes:
      - ./mongoDB-data:/data/db
    ports:
      - "27018:27017"
    networks:
      - course-enrolment-network

  enrolment-service-app:
    build:
      context: ./enrolment-Service
    container_name: "enrolment-service-app"
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongodb
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3000
      - QUEUE=enrolment-email
      - MONGO_URI=mongodb://mongodb:27017/
    networks:
      - course-enrolment-network

  email-service-app:
    build:
      context: ./email-Service
    deploy:
      replicas: 3
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - QUEUE=enrolment-email
    networks:
      - course-enrolment-network

networks:
  course-enrolment-network:
    driver: bridge
